linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gocyclo
    - gosec
    - prealloc
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    min-confidence: 0.8
  gosec:
    excludes:
      - G204  # Subprocess launching with variable

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
